/* =========================================================
   ملف التحكم بالموقع
   عدّل النصوص من هنا فقط. بعد الحفظ، حدّث الصفحة.
   لاستبدال السيرة: ضع ملفك مكان
   assets/cv/Ahmad-Eliwi-CV.pdf
   لإظهار صورتك: ضعها باسم
   assets/portrait.jpg
   ========================================================= */

window.PORTFOLIO = {
  person: {
    nameLines: {
      ar: ["أحمد", "عليوي"],
      en: ["Ahmad", "Eliwi"],
    },
    altName: {
      ar: "Ahmad Eliwi",
      en: "أحمد عليوي",
    },
    role: {
      ar: "مهندس برمجيات",
      en: "Software Engineer",
    },
    university: {
      ar: "جامعة دمشق",
      en: "Damascus University",
    },
    location: {
      ar: "دمشق، سوريا",
      en: "Damascus, Syria",
    },
    email: "ahmadadd619@gmail.com",
    phoneDisplay: "0943 893 722",
    phoneIntl: "+963 943 893 722",
    phoneTel: "+963943893722",
    whatsapp: "https://wa.me/963943893722",
    github: "https://github.com/Eliwi234",
    githubUser: "Eliwi234",
    cvFile: "assets/cv/Ahmad-Eliwi-CV.pdf",
    cvPage: "cv.html",
    vcard: "assets/contact/Ahmad-Eliwi.vcf",
    portrait: "assets/portrait.jpg",
  },

  ui: {
    ar: {
      "meta.title": "أحمد عليوي — مهندس برمجيات",
      "meta.description":
        "بورتفوليو أحمد عليوي، مهندس برمجيات خريج جامعة دمشق. منتجات ويب، أنظمة Laravel وReact، وتجارب تعليمية عربية، ونظام استرجاع معلومات.",
      "nav.work": "الأعمال",
      "nav.about": "نبذة",
      "nav.companies": "الشركات",
      "nav.skills": "المهارات",
      "nav.contact": "تواصل",
      "nav.cv": "السيرة",
      "nav.menu": "القائمة",
      "hero.eyebrow": "مهندس برمجيات · جامعة دمشق",
      "hero.lead":
        "أبني منتجات تُستخدم فعلاً: واجهات عربية دقيقة، أنظمة كاملة من الشاشة إلى قاعدة البيانات، ومسارات بحث تفرّق بين الكلمة ومعناها.",
      "hero.primary": "شاهد الأعمال",
      "hero.companies": "الشركات",
      "hero.secondary": "تواصل معي",
      "hero.cardKicker": "الآن",
      "hero.cardTitle": "أبحث عن عمل أترك فيه أثراً واضحاً في المنتج.",
      "hero.cardBody":
        "من لوحة تحكم حيّة إلى محرّك استرجاع معلومات. دمشق نقطة الانطلاق، والكود هو العنوان.",
      "hero.fact1": "خريج جامعة دمشق",
      "hero.fact2": "واجهات وأنظمة خلفية",
      "hero.fact3": "عربي وإنجليزي على المنتج",
      "about.kicker": "نبذة",
      "about.title": "هندسة تُرى على الشاشة، وتثبت في الخلف.",
      "about.body":
        "تخرّجت من جامعة دمشق مهندس برمجيات. أشتغل على المنتج كما يصله الإنسان: اتجاه الكتابة، وضوح الواجهة، وصحة البيانات والصلاحيات خلفها. في الواجهة أستخدم React وTypeScript، وفي الخادم Laravel أو FastAPI، وفي البحث أجمع BM25 مع التمثيل الدلالي ثم أقيس النتيجة.",
      "about.p1t": "الدراسة",
      "about.p1d": "جامعة دمشق — هندسة البرمجيات",
      "about.p2t": "المكان",
      "about.p2d": "دمشق، سوريا",
      "about.p3t": "طريقة العمل",
      "about.p3d": "منتج كامل: واجهة، واجهة برمجية، وبيانات",
      "about.p4t": "اللغات",
      "about.p4d": "العربية، والإنجليزية في العمل التقني",
      "companies.kicker": "الشركات",
      "companies.title": "أماكن اشتغلت فيها.",
      "companies.lead": "اختر شركة، أو استخدم السابق والتالي. التفاصيل نفسها المكتوبة في السيرة.",
      "companies.prev": "السابقة",
      "companies.next": "التالية",
      "project.more": "التفاصيل",
      "project.zoom": "تكبير الصورة",
      "project.close": "إغلاق",
      "work.kicker": "الأعمال",
      "work.title": "مشاريع مشروحة، لا لائحة روابط.",
      "work.lead":
        "كل بطاقة تلخّص ماذا يفعل المشروع، بماذا بُني، وأين يُفتح. الأرقام هي ترتيب العرض.",
      "filter.all": "الكل",
      "filter.product": "منتجات",
      "filter.system": "أنظمة",
      "filter.learning": "تعليم",
      "project.live": "الموقع",
      "project.front": "الواجهة",
      "project.back": "الخادم",
      "project.code": "الكود",
      "project.updated": "آخر تحديث",
      "kind.product": "منتج",
      "kind.system": "نظام",
      "kind.learning": "تعليم",
      "skills.kicker": "المهارات",
      "skills.title": "أدوات ظهرت في العمل، لا في سيرة منمّقة.",
      "skills.lead": "مجمّعة من المشاريع المنشورة على GitHub.",
      "cv.kicker": "السيرة الذاتية",
      "cv.title": "ملف واحد، يأخذه الزائر مباشرة.",
      "cv.lead":
        "السيرة مرفقة داخل الموقع. الزر الأول ينزّل ملف PDF، والثاني يفتح النسخة الكاملة للعرض والطباعة.",
      "cv.download": "تنزيل السيرة PDF",
      "cv.view": "عرض السيرة",
      "cv.note": "لاستبدال الملف لاحقاً، ضع سيرتك في نفس المسار داخل المستودع.",
      "contact.kicker": "تواصل",
      "contact.title": "البريد، الهاتف، وواتساب. بلا وسيط.",
      "contact.lead":
        "أقرأ الرسائل بنفسي. اختر القناة المناسبة، أو اكتب رسالتك وسيفتح تطبيق البريد ومعها النص جاهزاً.",
      "contact.email": "البريد",
      "contact.phone": "الهاتف",
      "contact.whatsapp": "واتساب",
      "contact.github": "غيت هب",
      "contact.location": "المكان",
      "contact.copy": "نسخ",
      "contact.copied": "تم النسخ",
      "contact.save": "حفظ جهة الاتصال",
      "contact.formName": "الاسم",
      "contact.formEmail": "بريدك",
      "contact.formMessage": "الرسالة",
      "contact.send": "فتح الرسالة في البريد",
      "contact.note": "الإرسال يفتح تطبيق البريد على جهازك. لا تُخزَّن الرسالة على هذا الموقع.",
      "contact.subject": "رسالة من البورتفوليو",
      "footer.note": "موقع ثابت أملك محتواه بالكامل.",
      "empty": "لا مشاريع ضمن هذا التصنيف.",
    },
    en: {
      "meta.title": "Ahmad Eliwi — Software Engineer",
      "meta.description":
        "Portfolio of Ahmad Eliwi, a software engineer and Damascus University graduate. Web products, Laravel and React systems, Arabic learning experiences, and an information-retrieval engine.",
      "nav.work": "Work",
      "nav.about": "About",
      "nav.companies": "Companies",
      "nav.skills": "Skills",
      "nav.contact": "Contact",
      "nav.cv": "CV",
      "nav.menu": "Menu",
      "hero.eyebrow": "Software Engineer · Damascus University",
      "hero.lead":
        "I build software people actually open: precise Arabic interfaces, systems that run from the screen to the database, and search that can tell a word from its meaning.",
      "hero.primary": "See the work",
      "hero.companies": "Companies",
      "hero.secondary": "Contact",
      "hero.cardKicker": "Now",
      "hero.cardTitle": "Looking for work where the product can feel the engineering.",
      "hero.cardBody":
        "From a live operations dashboard to an information-retrieval engine. Damascus is home. The code is the address.",
      "hero.fact1": "Damascus University graduate",
      "hero.fact2": "Interfaces and backends",
      "hero.fact3": "Arabic and English products",
      "about.kicker": "About",
      "about.title": "Engineering you can see, and engineering that holds.",
      "about.body":
        "I graduated from Damascus University as a software engineer. I care about the product as a person meets it: writing direction, interface clarity, and the data and permissions behind it. On the front I use React and TypeScript. On the server, Laravel or FastAPI. In search, I join BM25 with semantic embeddings and then measure the result.",
      "about.p1t": "Education",
      "about.p1d": "Damascus University — Software Engineering",
      "about.p2t": "Based in",
      "about.p2d": "Damascus, Syria",
      "about.p3t": "How I work",
      "about.p3d": "Whole products: interface, API, and data",
      "about.p4t": "Languages",
      "about.p4d": "Arabic, and English for technical work",
      "companies.kicker": "Companies",
      "companies.title": "Places I have worked.",
      "companies.lead": "Pick a company, or use previous and next. The details match the CV.",
      "companies.prev": "Previous",
      "companies.next": "Next",
      "project.more": "Details",
      "project.zoom": "Enlarge image",
      "project.close": "Close",
      "work.kicker": "Selected work",
      "work.title": "Projects with a description, not a link dump.",
      "work.lead": "Each card says what it does, what it is built with, and where to open it.",
      "filter.all": "All",
      "filter.product": "Products",
      "filter.system": "Systems",
      "filter.learning": "Learning",
      "project.live": "Live",
      "project.front": "Frontend",
      "project.back": "Backend",
      "project.code": "Code",
      "project.updated": "Updated",
      "kind.product": "Product",
      "kind.system": "System",
      "kind.learning": "Learning",
      "skills.kicker": "Skills",
      "skills.title": "Tools that showed up in the work.",
      "skills.lead": "Grouped from the repositories published on GitHub.",
      "cv.kicker": "Curriculum vitae",
      "cv.title": "One file. The visitor takes it with them.",
      "cv.lead":
        "The CV is attached to this site. The first button downloads the PDF. The second opens the full version for reading and printing.",
      "cv.download": "Download CV PDF",
      "cv.view": "View the CV",
      "cv.note": "To replace it later, drop your file on the same path in the repository.",
      "contact.kicker": "Contact",
      "contact.title": "Email, phone, and WhatsApp. No middleman.",
      "contact.lead":
        "I read the messages myself. Pick a channel, or write here and your mail app will open with the text ready.",
      "contact.email": "Email",
      "contact.phone": "Phone",
      "contact.whatsapp": "WhatsApp",
      "contact.github": "GitHub",
      "contact.location": "Location",
      "contact.copy": "Copy",
      "contact.copied": "Copied",
      "contact.save": "Save contact",
      "contact.formName": "Name",
      "contact.formEmail": "Your email",
      "contact.formMessage": "Message",
      "contact.send": "Open in email",
      "contact.note": "Sending opens the email app on your device. This site does not store the message.",
      "contact.subject": "Message from the portfolio",
      "footer.note": "A static site. The content stays mine to edit.",
      "empty": "Nothing in this filter.",
    },
  },

  companies: [
    {
      id: "hyper",
      name: "Hyper Net Company",
      role: {
        ar: "قسم الفحص (واي فاي خارجي) وفني تركيب",
        en: "Checks Department (Wifi Outdoor) & Installation Technician",
      },
      points: {
        ar: [
          "عملت في قسم الفحص لخدمات الواي فاي الخارجي.",
          "ركّبت أنظمة الواي فاي الخارجي وصنتها.",
        ],
        en: [
          "Worked in the checks department for Wifi Outdoor services.",
          "Performed installation and maintenance of Wifi Outdoor systems.",
        ],
      },
    },
    {
      id: "minicode",
      name: "Minicodeleader Platform",
      role: {
        ar: "مدرّس لغات البرمجة وأطر العمل",
        en: "Programming Languages and Frameworks Instructor",
      },
      points: {
        ar: ["أدرّس الطلاب لغات برمجة وأطر عمل، منها React وFlutter."],
        en: [
          "Instructing students in various programming languages and frameworks including React and Flutter.",
        ],
      },
    },
    {
      id: "english-online",
      name: "Online English School",
      role: {
        ar: "مدرّس لغة إنجليزية",
        en: "English Language Instructor",
      },
      points: {
        ar: ["أدرّس اللغة الإنجليزية للطلاب عبر منصة على الإنترنت."],
        en: ["Teaching English language to students through an online platform."],
      },
    },
    {
      id: "klibbadr",
      name: "Klibbadr School",
      role: {
        ar: "معلم لغة إنجليزية",
        en: "English Teacher",
      },
      points: {
        ar: ["درّست اللغة الإنجليزية للطلاب، وطوّرت مهارات التواصل والتنظيم."],
        en: [
          "Taught English language to students, developing strong communication and organizational skills.",
        ],
      },
    },
    {
      id: "abnaa",
      name: "Abnaa Algolan Team",
      role: {
        ar: "متطوّع",
        en: "Volunteer",
      },
      points: {
        ar: ["ساهمت في مبادرات مجتمعية، بعمل جماعي وقيادة والتزام."],
        en: [
          "Contributed to community initiatives, demonstrating teamwork, leadership, and commitment.",
        ],
      },
    },
  ],

  projects: [
    {
      id: "kitchenx",
      kind: "product",
      year: "2026",
      visual: "kitchen",
      image: "assets/projects/kitchenx.jpg",
      title: "KitchenX",
      summary: {
        ar: "منصة تربط الطهاة المنزليين بعشّاق الطعام، مع لوحة تشغيل تغطي اليوم كاملًا: من الوجبة إلى السائق فالتسوية.",
        en: "A platform that connects home chefs with people who want their food, and an operations desk that covers the day from the meal to the driver to the settlement.",
      },
      points: {
        ar: [
          "حسابات للدخول، وطهاة، وتصنيفات، ووجبات، وطلبات.",
          "سائقون، عملاء، كوبونات، تسويات، وتقارير.",
          "إشعارات لحظية عبر Laravel Echo وPusher.",
          "واجهة عربية وإنجليزية، ونماذج تُفحص قبل الإرسال.",
        ],
        en: [
          "Sign-in, chefs, categories, meals, and orders.",
          "Drivers, customers, coupons, settlements, and reports.",
          "Realtime notifications with Laravel Echo and Pusher.",
          "Arabic and English UI, with forms checked before submit.",
        ],
      },
      stack: ["React 19", "TypeScript", "Vite", "Tailwind", "Zustand", "TanStack Query", "Zod", "i18next"],
      links: [
        { type: "live", href: "https://kitchenx.vercel.app" },
        { type: "code", href: "https://github.com/Eliwi234/kitchenX" },
      ],
    },
    {
      id: "ir",
      kind: "system",
      year: "2026",
      visual: "search",
      image: "assets/projects/ir.jpg",
      title: { ar: "نظام استرجاع المعلومات", en: "Information Retrieval System" },
      summary: {
        ar: "مسار بحث كامل بمعمارية خدمات: فهرسة، ترتيب، تقييم، ثم إجابة مبنية على المستندات. يدعم مجموعات CORD-19 وMS MARCO.",
        en: "A full search pipeline in a service architecture: index, rank, evaluate, then answer from the documents. Built for CORD-19 and MS MARCO.",
      },
      points: {
        ar: [
          "TF-IDF وBM25 وSentence-BERT، ودمج النتائج بـ RRF.",
          "إعادة ترتيب بإشارات متعددة، وقياس MAP وnDCG وPrecision.",
          "تصحيح الاستعلام، بحث متعدد اللغات، ونمذجة مواضيع.",
          "بوابة FastAPI، واجهة Streamlit، وتخزين النص في SQLite.",
        ],
        en: [
          "TF-IDF, BM25, and Sentence-BERT, fused with reciprocal rank fusion.",
          "Multi-signal reranking, measured with MAP, nDCG, and precision.",
          "Query refinement, multilingual search, and topic modeling.",
          "A FastAPI gateway, a Streamlit desk, and document text in SQLite.",
        ],
      },
      stack: ["Python", "FastAPI", "Streamlit", "scikit-learn", "SBERT", "FAISS", "SQLite", "NLTK"],
      links: [{ type: "code", href: "https://github.com/Eliwi234/IR_project" }],
    },
    {
      id: "curriculum",
      kind: "learning",
      year: "2026",
      visual: "curriculum",
      image: "assets/projects/curriculum.jpg",
      title: { ar: "منهج بايثون المتكامل", en: "Integrated Python Curriculum" },
      summary: {
        ar: "موقع منهج عربي للمعاهد التقنية، من الصفر باتجاه العمل: أربعة مستويات، فهرس دروس، ومساحة للتمارين والمشاريع التطبيقية.",
        en: "An Arabic curriculum site for technical institutes, moving from zero toward practice: four levels, a lesson index, and room for exercises and applied projects.",
      },
      points: {
        ar: [
          "المستوى الأول يغطي البيئة، المتغيرات، الشرط، التكرار، والمجموعات.",
          "المستويات التالية تبني على ذلك نحو مواضيع أوسع.",
          "فهرس واضح وتنقّل بين الدروس والمستويات.",
          "واجهة عربية كُتبت لتُقرأ براحة على الشاشة.",
        ],
        en: [
          "Level one covers the environment, variables, conditions, loops, and collections.",
          "Later levels build on that toward broader topics.",
          "A clear index and movement between lessons and levels.",
          "An Arabic interface written to be read comfortably on screen.",
        ],
      },
      stack: ["HTML", "CSS", "JavaScript", "Cairo", "Arabic UI"],
      links: [
        { type: "live", href: "https://python-roadmap-zeta.vercel.app" },
        { type: "code", href: "https://github.com/Eliwi234/PYTHON-ROADMAP" },
      ],
    },
    {
      id: "adventure",
      kind: "learning",
      year: "2026",
      visual: "learn",
      image: "assets/projects/adventure.jpg",
      title: "Python Adventure",
      summary: {
        ar: "بوابة تفاعلية لتعلّم بايثون من الصفر. المهمّة الأولى تطلب سطرًا يجعل الحاسوب يقول مرحبًا، ثم تكمل الجلسات مع نسبة تقدّم.",
        en: "An interactive door into Python from zero. The first mission asks for the line that makes the computer say hello, then sessions continue with a progress trail.",
      },
      points: {
        ar: [
          "دخول بالاسم إلى لوحة المنهج والجلسات والملفات.",
          "مهمات قصيرة مع تلميح مباشر، مثل استخدام print.",
          "لمسة لعب خفيفة حتى لا تجفّ الصفحة على المبتدئ.",
          "React وTailwind وحركة عبر Framer Motion.",
        ],
        en: [
          "A name-based entry into the syllabus, sessions, and files.",
          "Short missions with a direct hint, such as using print.",
          "A light playful note so the page does not go dry for a beginner.",
          "React, Tailwind, and motion with Framer Motion.",
        ],
      },
      stack: ["React 19", "Vite", "Tailwind", "Framer Motion"],
      links: [
        { type: "live", href: "https://python1-course-mu.vercel.app" },
        { type: "code", href: "https://github.com/Eliwi234/python1_course" },
      ],
    },
    {
      id: "banking",
      kind: "system",
      year: "2025",
      visual: "bank",
      image: "assets/projects/bank.jpg",
      title: { ar: "نظام مصرفي متقدم", en: "Advanced Banking System" },
      summary: {
        ar: "نظام بحسابات وحركات وموافقات. الواجهة بـ React، والخادم بـ Laravel، مع تقارير ومسار لاستعادة الدخول.",
        en: "Accounts, movements, and approvals. The interface is React, the server is Laravel, with reports and a path back in when the password is lost.",
      },
      points: {
        ar: [
          "حسابات، حركات مالية، وتحويلات مجدولة.",
          "مستخدمون، موافقات، وتقارير.",
          "تذاكر دعم، وتسجيل دخول، وإعادة تعيين كلمة المرور.",
          "مستودع للواجهة وآخر للخادم.",
        ],
        en: [
          "Accounts, transactions, and scheduled transfers.",
          "Users, approvals, and reports.",
          "Support tickets, sign-in, and password reset.",
          "One repository for the interface, one for the server.",
        ],
      },
      stack: ["React", "Vite", "Tailwind", "Laravel", "PHP", "REST"],
      links: [
        { type: "front", href: "https://github.com/Eliwi234/Advanced-Bancking-System" },
        { type: "back", href: "https://github.com/Eliwi234/Advanced-Bancking-System-Backend" },
      ],
    },
    {
      id: "complaints",
      kind: "system",
      year: "2025",
      visual: "complaint",
      image: "assets/projects/cases.jpg",
      title: { ar: "نظام الشكاوى", en: "Complaints System" },
      summary: {
        ar: "مسار شكوى بين الإدارة والوكالة والموظف: النوع، القسم، المرفق، وسجل ما تغيّر على الشكوى.",
        en: "A complaint path between administration, agency, and employee: type, department, attachment, and a history of what changed.",
      },
      points: {
        ar: [
          "لوحات للإدارة والوكالة، ودخول للموظف.",
          "أنواع شكاوى وأقسام ومرفقات.",
          "سجل معالجة يحتفظ بأثر كل خطوة.",
          "واجهة React وخادم Laravel.",
        ],
        en: [
          "Desks for administration and the agency, plus employee sign-in.",
          "Complaint types, departments, and attachments.",
          "A handling history that keeps the trace of each step.",
          "A React interface and a Laravel server.",
        ],
      },
      stack: ["React", "Vite", "Laravel", "PHP", "REST"],
      links: [
        { type: "front", href: "https://github.com/Eliwi234/Compalint-System" },
        { type: "back", href: "https://github.com/Eliwi234/Compalint-System-backend" },
      ],
    },
    {
      id: "compiler",
      kind: "system",
      year: "2025",
      visual: "compiler",
      image: "assets/projects/compiler.jpg",
      title: { ar: "واجهة مترجم", en: "Compiler Front End" },
      summary: {
        ar: "مترجم بلغة جافا لقواعد ببناء Angular: تحليل معجمي ونحوي، شجرة بناء، جدول رموز، ثم تمريرة تُظهر الأخطاء الدلالية.",
        en: "A Java compiler front end for an Angular-shaped grammar: lexing, parsing, an abstract tree, a symbol table, then a pass that surfaces semantic errors.",
      },
      points: {
        ar: [
          "Lexer وParser مولَّدان بـ ANTLR.",
          "شجرة AST تمثّل البرنامج بعد التحليل.",
          "جدول رموز وVisitor للفحص الدلالي.",
          "تشغيل على ملفات اختبار وعرض الأخطاء.",
        ],
        en: [
          "Lexer and parser generated with ANTLR.",
          "An AST that represents the program after parsing.",
          "A symbol table and a visitor for semantic checks.",
          "Runs on test files and prints the errors.",
        ],
      },
      stack: ["Java", "ANTLR", "AST", "Symbol Table", "Visitor"],
      links: [{ type: "code", href: "https://github.com/Eliwi234/ProjectCompiler2" }],
    },
    {
      id: "wifi",
      kind: "product",
      year: "2026",
      visual: "wifi",
      image: "assets/projects/wifi.jpg",
      title: "HyperWifi",
      summary: {
        ar: "صفحة هبوط عربية لطلب اشتراك إنترنت: بيانات المكان، عدد الطوابق، وباقة السرعة، ثم تُرسل الرسالة منسّقة عبر واتساب.",
        en: "An Arabic landing page for an internet subscription: place, floors, and speed package, then the request leaves as a formatted WhatsApp message.",
      },
      points: {
        ar: [
          "نموذج يطلب الحقول اللازمة قبل الإرسال.",
          "اختيار باقة السرعة ونوع الاشتراك.",
          "تحقق من النواقص ورسالة خطأ واضحة.",
          "تسليم الطلب إلى واتساب بدل نموذج يضيع.",
        ],
        en: [
          "A form that asks for the fields it needs before sending.",
          "Speed package and subscription type.",
          "Missing fields are caught with a clear error.",
          "The request is handed to WhatsApp instead of a form that vanishes.",
        ],
      },
      stack: ["HTML", "CSS", "JavaScript", "WhatsApp"],
      links: [{ type: "code", href: "https://github.com/Eliwi234/HyperWifi" }],
    },
  ],

  skills: [
    {
      title: { ar: "الواجهات", en: "Interfaces" },
      items: ["HTML", "CSS", "JavaScript", "TypeScript", "React", "Vite", "Tailwind CSS", "Framer Motion"],
    },
    {
      title: { ar: "الخوادم", en: "Servers" },
      items: ["PHP", "Laravel", "REST", "FastAPI", "Python"],
    },
    {
      title: { ar: "البحث والبيانات", en: "Search and data" },
      items: ["BM25", "TF-IDF", "Sentence-BERT", "FAISS", "scikit-learn", "NLTK", "SQLite", "Streamlit"],
    },
    {
      title: { ar: "الأنظمة والأدوات", en: "Systems and tools" },
      items: ["Java", "ANTLR", "Git", "GitHub", "Vercel", "i18n"],
    },
  ],
};
